[tool.poetry]
name = "resultsdb"
version = "2.2.0"
description = "The test results store engine for (not only) Fedora QA tools"
authors = [
  "Red Hat, Inc. and others"
]
license = "GPL-2.0-or-later"
readme = "README.md"
repository = "https://github.com/release-engineering/resultsdb"
homepage = "http://docs.resultsdb20.apiary.io/"

include = [
    "LICENSE",
    "README.md",
    "alembic.ini",
    "tox.ini",
    "resultsdb/templates/*",
    "resultsdb/static/*",
    "resultsdb/alembic/*",
]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
flask = "^2.1.3"
gunicorn = "^20.1.0"
fedora-messaging = "^3.2.0"
"stomp.py" = "^8.1.0"

flake8 = {version = "^6.0.0", optional = true}
pytest = {version = "^7.2.0", optional = true}
pytest-cov = {version = "^4.0.0", optional = true}
tox = {version = "4.0.0rc1", optional = true}
tox-docker = {version = "4.0.0a2", optional = true}

flask-oidc = "^1.4.0"
Flask-SQLAlchemy = "^3.0.2"
SQLAlchemy = {version = "^1.4.39"}
psycopg2-binary = {version = "^2.9.3"}
alembic = "^1.9.1"
iso8601 = "^1.0.2"
Flask-Pydantic = "^0.11.0"

# https://github.com/puiterwijk/flask-oidc/issues/147
itsdangerous = {version = "==2.0.1", optional = true}

email-validator = "^1.3.0"
python-ldap = "^3.4.3"

[tool.poetry.extras]
test = [
    "flake8",
    "pytest",
    "pytest-cov",
    "tox",
    "tox-docker",
]

[tool.poetry.scripts]
resultsdb = "resultsdb.__main__:cli"

[tool.poetry.plugins."resultsdb.messaging.plugins"]
dummy = "resultsdb.messaging:DummyPlugin"
fedmsg = "resultsdb.messaging:FedmsgPlugin"
stomp = "resultsdb.messaging:StompPlugin"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
