[project]
name = "resultsdb"
version = "2.2.0"
description = "The test results store engine for (not only) Fedora QA tools"
authors = [
    {name = "Red Hat, Inc. and others"}
]
license = {text = "GPL-2.0-or-later"}
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "flask>=3.0.1,<4.0.0",
    "gunicorn>=25.0.0,<25.1.0",
    "fedora-messaging>=3.4.1,<4.0.0",
    "stomp-py>=8.2.0,<9.0.0",
    "Flask-SQLAlchemy>=3.1.1,<4.0.0",
    "SQLAlchemy>=2.0.36,<3.0.0",
    "psycopg2-binary>=2.9.10,<3.0.0",
    "alembic>=1.13.3,<2.0.0",
    "iso8601>=2.1.0,<3.0.0",
    "pydantic>=2.10.2,<3.0.0",
    "Flask-Pydantic>=0.13.0,<1.0.0",
    "email-validator>=2.2.0,<3.0.0",
    "python-ldap>=3.4.3,<4.0.0",
    "Flask-pyoidc>=3.14.3,<4.0.0",
    "Flask-Session>=0.8.0,<1.0.0",
    "opentelemetry-exporter-otlp>=1.25.0,<2.0.0",
    "opentelemetry-instrumentation>=0.46b0,<1.0.0",
    "opentelemetry-instrumentation-flask>=0.46b0,<1.0.0",
    "opentelemetry-instrumentation-sqlalchemy>=0.46b0,<1.0.0",
    "tenacity>=9.0.0,<10.0.0",
    "setuptools>=80.9.0",
    "mod-wsgi>=5.0.2",
]

[project.optional-dependencies]
test = [
    "pytest>=9.0.0,<9.1.0",
    "pytest-cov>=7.0.0,<8.0.0",
]

[project.scripts]
resultsdb = "resultsdb.__main__:cli"

[project.entry-points."resultsdb.messaging.plugins"]
dummy = "resultsdb.messaging:DummyPlugin"
fedmsg = "resultsdb.messaging:FedmsgPlugin"
stomp = "resultsdb.messaging:StompPlugin"

[project.urls]
Homepage = "https://docs.resultsdb20.apiary.io/"
Repository = "https://github.com/release-engineering/resultsdb"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["resultsdb"]

[tool.hatch.build.targets.sdist]
include = [
    "/resultsdb",
    "/conf",
    "/LICENSE",
    "/README.md",
    "/alembic.ini",
    "/tox.ini",
]
