"""Create indexes on Foreign Keys

Revision ID: 153c416322c2
Revises: 17ec41bd6e9a
Create Date: 2015-04-14 14:30:03.096651

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "153c416322c2"
down_revision = "17ec41bd6e9a"
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index("result_fk_job_id", "result", ["job_id"], unique=False)
    op.create_index("result_fk_testcase_id", "result", ["testcase_id"], unique=False)
    op.create_index(
        "result_data_fk_result_id", "result_data", ["result_id"], unique=False
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("result_data_fk_result_id", table_name="result_data")
    op.drop_index("result_fk_testcase_id", table_name="result")
    op.drop_index("result_fk_job_id", table_name="result")
    ### end Alembic commands ###
