"""Added index on the Keyval store

Revision ID: 433d0b5b3b96
Revises: 15f5eeb9f635
Create Date: 2015-02-24 19:57:57.643189

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "433d0b5b3b96"
down_revision = "15f5eeb9f635"
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "rd_key_value_idx",
        "result_data",
        ["key", "value"],
        unique=False,
        mysql_length={"value": 50, "key": 20},
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("rd_key_value_idx", table_name="result_data")
    ### end Alembic commands ###
