"""Added index on submit_time

Revision ID: 4bf1390f06d1
Revises: 34760e10040b
Create Date: 2015-11-03 13:06:35.167227

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "4bf1390f06d1"
down_revision = "34760e10040b"
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index("result_submit_time", "result", ["submit_time"], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("result_submit_time", table_name="result")
    ### end Alembic commands ###
