---
name: ResultsDB

"on":
  pull_request:
  push:
  workflow_dispatch:
    inputs: {}

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install uv
        uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24 # v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        uses: nick-invision/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3
        with:
          timeout_minutes: 10
          retry_wait_seconds: 30
          max_attempts: 3
          command: >-
            sudo apt-get update
            && sudo apt-get install
            apache2-dev
            libkrb5-dev
            libldap2-dev
            libsasl2-dev

      - name: Test with tox
        run: uvx --with tox-uv tox -e py3

      - name: Run coveralls-python
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: python-${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
        run: |
          uvx --with coveralls coveralls --service=github

      - name: Upload coverage to Coveralls
        run: |
          uvx --with coveralls coveralls --finish --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - Dockerfile

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          dockerfile: ${{ matrix.dockerfile }}
          # Ignore list:
          # * DL3041 - Specify version with dnf install -y <package>-<version>
          ignore: DL3041
          failure-threshold: warning
